FROM openjdk:21-jdk-slim

WORKDIR /app

COPY target/GatewayService-0.0.1-SNAPSHOT.jar app.jar

# Copy the application properties file based on the environment
COPY src/main/resources/application-docker.properties application.properties

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]